### ISSUE TITLE
Can't deploy on Heroku

### ISSUE THREAD

**Issue by RobertoBarros** [torba-rb/torba-rails#3]
I'm trying to deploy a rails application with Torba on heroku, but the `asset:precompile` don't run the `torba pack`. The variables `TORBA_HOME_PATH` and `TORBA_CACHE_PATH` are setted in the Heroku config vars. The log of heroku deploy is:

```
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        Torba::Errors::MissingPackages: [#<Torba::Package:0x007ff5636fb980 @name="tooltipster", @remote_source=#<Torba::RemoteSources::GithubRelease:0x007ff563704a08 @source="iamceege/tooltipster", @tag="3.2.6", @repository_user="iamceege", @repository_name="tooltipster", @url="https://github.com/iamceege/tooltipster/archive/3.2.6.zip", @digest="tooltipster-a0a331b0">, @import_paths=["css/themes/tooltipster-light.css", "css/tooltipster.css", "js/jquery.tooltipster.js"], @load_path="vendor/torba/tooltipster-edaec908">]
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/torba-1.0.0/lib/torba/manifest.rb:121:in `verify'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/torba-1.0.0/lib/torba.rb:69:in `verify'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/torba-1.0.0/lib/torba/verify.rb:6:in `<top (required)>'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/torba-rails-1.0.0/lib/torba/rails.rb:17:in `block in <class:Engine>'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:352:in `initialize!'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:328:in `require'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:328:in `require_environment!'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_d7409fa1557cbbf8209532e4c0425163/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.1/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed

```

I tested the `https://github.com/torba-rb/torba-rails` deploy on heroku and get the same error.

Any idea why the `torba pack` is not running in the `asset:precompile`?

**Comment by nashbridges** [comment]
torba-rails relies on "serve assets" setting when deciding whether to perform imported assets verification (and possibly raise an error) or not. It was kinda smart way to avoid checking for dev/production modes, but I completely forgot that Heroku serves assets in production.

**Comment by nashbridges** [comment]
@RobertoBarros could you please check if linked PR fixes the problem?

**Comment by RobertoBarros** [comment]
@nashbridges The fix is working. I tested with a Rails 4 and Rails 5 apps. Thanks!

**Comment by nashbridges** [comment]
OK. Let me investigate why Travis builds have started failing, and I will release a fix.
Until when you can use my fork.

**Comment by nashbridges** [comment]
@RobertoBarros I know it's *too* late for a release, but in case you're still using the gem, its [1.0.2 version](https://rubygems.org/gems/torba-rails/versions/1.0.2) contains the fix.

I haven't removed the branch yet (again, in case you're still using it).
